### ISSUE TITLE
Error DL firmware

### ISSUE THREAD

**Issue by stef-ladefense** [folkemat/KoboPatchFan#1]
hi,
i test your program, nice !
but have pb
have aura, when choise last fw, dl zip file of 322 bytes ...
your prog use https://kbdownload1-a.akamaihd.net/firmwares/kobo5/Aug2023/kobo-update-4.38.21908.zip
have open file : 
`Invalid URL
The requested URL "http://%5bNo%20Host%5d/firmwares/kobo5/Aug2023/kobo-update-4.38.21908.zip", is invalid.
Reference #9.c9691160.1696392949.7007bafc`

when manual dl fw in https://cdn.kobo.com/downloads/firmwares/kobo5/Aug2023/kobo-update-4.38.21908.zip
and copy in folder, your prog work fine

stef

**Comment by folkemat** [comment]
There was indeed a problem with the download links in the database. This has now been fixed. Click on "Update database" and the download will work.
