### ISSUE TITLE
Program does not have the right firmware for Kobo Libra 2

### ISSUE THREAD

**Issue by asimard1** [folkemat/KoboPatchFan#2]
The program says that the found firmware is 4.4.9298 but the latest firmware version is 4.38.21908. Is the program just not updated anymore?

**Comment by folkemat** [comment]
I've seen several times now that this confuses people. I'm going to change it so that the latest version is always selected automatically without having to click on the button

**Comment by asimard1** [comment]
Thank you so much for your work !
